### ISSUE TITLE
[critical] Uncaught Exception: You have requested a non-existent parameter "pimcore.config".

### ISSUE THREAD

**Issue by alexej-d** [dachcom-digital/pimcore-jobs#19]
| Q                | A
| ---------------- | -----
| Bug report?      | yes
| Feature request? | no
| BC Break report? |no
| RFC?             | no

Installing this bundle with Pimcore 11 is impossible. The command `bin/console pimcore:bundle:install JobsBundle
` throws the error in the title. Seems like this bundle is abandoned?

**Comment by solverat** [comment]
@alexej-d Nope, this bundle is not abandoned. I'm also not able to reproduce this issue.
Which jobs version do you use and also which pimcore version do you use?

I successfully installed it within pimcore 11.2, 11.3 and 11.4

**Comment by solverat** [comment]
@alexej-d yes, it does:

https://github.com/pimcore/pimcore/blob/518a14d738b74d167ac8219ea4c92cf45826c0c0/bundles/CoreBundle/src/DependencyInjection/Compiler/AreabrickPass.php#L49

**Comment by solverat** [comment]
Ok, i got it. This only happens if there is no job configuration available. I guess `pimcore.config` is not available at this point.
I'll check! Thanks!

**Comment by solverat** [comment]
@alexej-d fixed and released with [3.0.1](https://github.com/dachcom-digital/pimcore-jobs/releases/tag/v3.0.1).
